package com.sinosoft.aiqc.db.dao;

import com.sinosoft.aiqc.db.domain.YyzjCThreshold;
import com.sinosoft.aiqc.db.domain.YyzjCThresholdExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YyzjCThresholdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_threshold
     *
     * @mbg.generated
     */
    long countByExample(YyzjCThresholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_threshold
     *
     * @mbg.generated
     */
    int deleteByExample(YyzjCThresholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_threshold
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String thresholdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_threshold
     *
     * @mbg.generated
     */
    int insert(YyzjCThreshold record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_threshold
     *
     * @mbg.generated
     */
    int insertSelective(YyzjCThreshold record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_threshold
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjCThreshold selectOneByExample(YyzjCThresholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_threshold
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjCThreshold selectOneByExampleSelective(@Param("example") YyzjCThresholdExample example, @Param("selective") YyzjCThreshold.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_threshold
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YyzjCThreshold> selectByExampleSelective(@Param("example") YyzjCThresholdExample example, @Param("selective") YyzjCThreshold.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_threshold
     *
     * @mbg.generated
     */
    List<YyzjCThreshold> selectByExample(YyzjCThresholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_threshold
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjCThreshold selectByPrimaryKeySelective(@Param("thresholdId") String thresholdId, @Param("selective") YyzjCThreshold.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_threshold
     *
     * @mbg.generated
     */
    YyzjCThreshold selectByPrimaryKey(String thresholdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_threshold
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YyzjCThreshold record, @Param("example") YyzjCThresholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_threshold
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YyzjCThreshold record, @Param("example") YyzjCThresholdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_threshold
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YyzjCThreshold record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_threshold
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YyzjCThreshold record);
}