package com.sinosoft.aiqc.db.dao;

import com.sinosoft.aiqc.db.domain.YyzjCScoreTotalResult;
import com.sinosoft.aiqc.db.domain.YyzjCScoreTotalResultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YyzjCScoreTotalResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total_result
     *
     * @mbg.generated
     */
    long countByExample(YyzjCScoreTotalResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total_result
     *
     * @mbg.generated
     */
    int deleteByExample(YyzjCScoreTotalResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total_result
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String totalScoreResultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total_result
     *
     * @mbg.generated
     */
    int insert(YyzjCScoreTotalResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total_result
     *
     * @mbg.generated
     */
    int insertSelective(YyzjCScoreTotalResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total_result
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjCScoreTotalResult selectOneByExample(YyzjCScoreTotalResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total_result
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjCScoreTotalResult selectOneByExampleSelective(@Param("example") YyzjCScoreTotalResultExample example, @Param("selective") YyzjCScoreTotalResult.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total_result
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YyzjCScoreTotalResult> selectByExampleSelective(@Param("example") YyzjCScoreTotalResultExample example, @Param("selective") YyzjCScoreTotalResult.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total_result
     *
     * @mbg.generated
     */
    List<YyzjCScoreTotalResult> selectByExample(YyzjCScoreTotalResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total_result
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjCScoreTotalResult selectByPrimaryKeySelective(@Param("totalScoreResultId") String totalScoreResultId, @Param("selective") YyzjCScoreTotalResult.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total_result
     *
     * @mbg.generated
     */
    YyzjCScoreTotalResult selectByPrimaryKey(String totalScoreResultId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total_result
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YyzjCScoreTotalResult record, @Param("example") YyzjCScoreTotalResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total_result
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YyzjCScoreTotalResult record, @Param("example") YyzjCScoreTotalResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YyzjCScoreTotalResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YyzjCScoreTotalResult record);
}