package com.sinosoft.aiqc.db.dao;

import com.sinosoft.aiqc.db.domain.YyzjTScoreDetailData;
import com.sinosoft.aiqc.db.domain.YyzjTScoreDetailDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YyzjTScoreDetailDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_detail_data
     *
     * @mbg.generated
     */
    long countByExample(YyzjTScoreDetailDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_detail_data
     *
     * @mbg.generated
     */
    int deleteByExample(YyzjTScoreDetailDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_detail_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String scoreDetailDataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_detail_data
     *
     * @mbg.generated
     */
    int insert(YyzjTScoreDetailData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_detail_data
     *
     * @mbg.generated
     */
    int insertSelective(YyzjTScoreDetailData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_detail_data
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjTScoreDetailData selectOneByExample(YyzjTScoreDetailDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_detail_data
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjTScoreDetailData selectOneByExampleSelective(@Param("example") YyzjTScoreDetailDataExample example, @Param("selective") YyzjTScoreDetailData.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_detail_data
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YyzjTScoreDetailData> selectByExampleSelective(@Param("example") YyzjTScoreDetailDataExample example, @Param("selective") YyzjTScoreDetailData.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_detail_data
     *
     * @mbg.generated
     */
    List<YyzjTScoreDetailData> selectByExample(YyzjTScoreDetailDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_detail_data
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjTScoreDetailData selectByPrimaryKeySelective(@Param("scoreDetailDataId") String scoreDetailDataId, @Param("selective") YyzjTScoreDetailData.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_detail_data
     *
     * @mbg.generated
     */
    YyzjTScoreDetailData selectByPrimaryKey(String scoreDetailDataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_detail_data
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YyzjTScoreDetailData record, @Param("example") YyzjTScoreDetailDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_detail_data
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YyzjTScoreDetailData record, @Param("example") YyzjTScoreDetailDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_detail_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YyzjTScoreDetailData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_detail_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YyzjTScoreDetailData record);
}