package com.sinosoft.aiqc.db.dao;

import com.sinosoft.aiqc.db.domain.YyzjSKeywordNumAgent;
import com.sinosoft.aiqc.db.domain.YyzjSKeywordNumAgentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YyzjSKeywordNumAgentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_keyword_num_agent
     *
     * @mbg.generated
     */
    long countByExample(YyzjSKeywordNumAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_keyword_num_agent
     *
     * @mbg.generated
     */
    int deleteByExample(YyzjSKeywordNumAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_keyword_num_agent
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String numAgentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_keyword_num_agent
     *
     * @mbg.generated
     */
    int insert(YyzjSKeywordNumAgent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_keyword_num_agent
     *
     * @mbg.generated
     */
    int insertSelective(YyzjSKeywordNumAgent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_keyword_num_agent
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjSKeywordNumAgent selectOneByExample(YyzjSKeywordNumAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_keyword_num_agent
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjSKeywordNumAgent selectOneByExampleSelective(@Param("example") YyzjSKeywordNumAgentExample example, @Param("selective") YyzjSKeywordNumAgent.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_keyword_num_agent
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YyzjSKeywordNumAgent> selectByExampleSelective(@Param("example") YyzjSKeywordNumAgentExample example, @Param("selective") YyzjSKeywordNumAgent.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_keyword_num_agent
     *
     * @mbg.generated
     */
    List<YyzjSKeywordNumAgent> selectByExample(YyzjSKeywordNumAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_keyword_num_agent
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjSKeywordNumAgent selectByPrimaryKeySelective(@Param("numAgentId") String numAgentId, @Param("selective") YyzjSKeywordNumAgent.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_keyword_num_agent
     *
     * @mbg.generated
     */
    YyzjSKeywordNumAgent selectByPrimaryKey(String numAgentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_keyword_num_agent
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YyzjSKeywordNumAgent record, @Param("example") YyzjSKeywordNumAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_keyword_num_agent
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YyzjSKeywordNumAgent record, @Param("example") YyzjSKeywordNumAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_keyword_num_agent
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YyzjSKeywordNumAgent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_keyword_num_agent
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YyzjSKeywordNumAgent record);
}