package com.sinosoft.aiqc.db.dao;

import com.sinosoft.aiqc.db.domain.YyzjCProducerEleGroup;
import com.sinosoft.aiqc.db.domain.YyzjCProducerEleGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YyzjCProducerEleGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_group
     *
     * @mbg.generated
     */
    long countByExample(YyzjCProducerEleGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_group
     *
     * @mbg.generated
     */
    int deleteByExample(YyzjCProducerEleGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String eleGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_group
     *
     * @mbg.generated
     */
    int insert(YyzjCProducerEleGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_group
     *
     * @mbg.generated
     */
    int insertSelective(YyzjCProducerEleGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_group
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjCProducerEleGroup selectOneByExample(YyzjCProducerEleGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_group
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjCProducerEleGroup selectOneByExampleSelective(@Param("example") YyzjCProducerEleGroupExample example, @Param("selective") YyzjCProducerEleGroup.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_group
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YyzjCProducerEleGroup> selectByExampleSelective(@Param("example") YyzjCProducerEleGroupExample example, @Param("selective") YyzjCProducerEleGroup.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_group
     *
     * @mbg.generated
     */
    List<YyzjCProducerEleGroup> selectByExample(YyzjCProducerEleGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_group
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjCProducerEleGroup selectByPrimaryKeySelective(@Param("eleGroupId") String eleGroupId, @Param("selective") YyzjCProducerEleGroup.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_group
     *
     * @mbg.generated
     */
    YyzjCProducerEleGroup selectByPrimaryKey(String eleGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_group
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YyzjCProducerEleGroup record, @Param("example") YyzjCProducerEleGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_group
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YyzjCProducerEleGroup record, @Param("example") YyzjCProducerEleGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YyzjCProducerEleGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YyzjCProducerEleGroup record);

    /**
     * 查询最大的GroupId
     * @return
     */
    String selectMaxGroupId();
}