package com.sinosoft.aiqc.db.dao;

import com.sinosoft.aiqc.db.domain.YyzjCScoreTotal;
import com.sinosoft.aiqc.db.domain.YyzjCScoreTotalExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YyzjCScoreTotalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total
     *
     * @mbg.generated
     */
    long countByExample(YyzjCScoreTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total
     *
     * @mbg.generated
     */
    int deleteByExample(YyzjCScoreTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String totalScoreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total
     *
     * @mbg.generated
     */
    int insert(YyzjCScoreTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total
     *
     * @mbg.generated
     */
    int insertSelective(YyzjCScoreTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjCScoreTotal selectOneByExample(YyzjCScoreTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjCScoreTotal selectOneByExampleSelective(@Param("example") YyzjCScoreTotalExample example, @Param("selective") YyzjCScoreTotal.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YyzjCScoreTotal> selectByExampleSelective(@Param("example") YyzjCScoreTotalExample example, @Param("selective") YyzjCScoreTotal.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total
     *
     * @mbg.generated
     */
    List<YyzjCScoreTotal> selectByExample(YyzjCScoreTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjCScoreTotal selectByPrimaryKeySelective(@Param("totalScoreId") String totalScoreId, @Param("selective") YyzjCScoreTotal.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total
     *
     * @mbg.generated
     */
    YyzjCScoreTotal selectByPrimaryKey(String totalScoreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YyzjCScoreTotal record, @Param("example") YyzjCScoreTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YyzjCScoreTotal record, @Param("example") YyzjCScoreTotalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YyzjCScoreTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_total
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YyzjCScoreTotal record);
}