package com.sinosoft.aiqc.db.dao;

import com.sinosoft.aiqc.db.domain.YyzjCScoreDetail;
import com.sinosoft.aiqc.db.domain.YyzjCScoreDetailExample;
import java.util.List;

import com.sinosoft.aiqc.db.domain.extend.RuleAndScoreDetail;
import org.apache.ibatis.annotations.Param;

public interface YyzjCScoreDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_detail
     *
     * @mbg.generated
     */
    long countByExample(YyzjCScoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_detail
     *
     * @mbg.generated
     */
    int deleteByExample(YyzjCScoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String detailScoreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_detail
     *
     * @mbg.generated
     */
    int insert(YyzjCScoreDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_detail
     *
     * @mbg.generated
     */
    int insertSelective(YyzjCScoreDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjCScoreDetail selectOneByExample(YyzjCScoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjCScoreDetail selectOneByExampleSelective(@Param("example") YyzjCScoreDetailExample example, @Param("selective") YyzjCScoreDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YyzjCScoreDetail> selectByExampleSelective(@Param("example") YyzjCScoreDetailExample example, @Param("selective") YyzjCScoreDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_detail
     *
     * @mbg.generated
     */
    List<YyzjCScoreDetail> selectByExample(YyzjCScoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjCScoreDetail selectByPrimaryKeySelective(@Param("detailScoreId") String detailScoreId, @Param("selective") YyzjCScoreDetail.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_detail
     *
     * @mbg.generated
     */
    YyzjCScoreDetail selectByPrimaryKey(String detailScoreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YyzjCScoreDetail record, @Param("example") YyzjCScoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YyzjCScoreDetail record, @Param("example") YyzjCScoreDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YyzjCScoreDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_score_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YyzjCScoreDetail record);

    List<RuleAndScoreDetail> selectByTotalScoreId(@Param("totalScoreId") String totalScoreId, @Param("ruleIds") List<String> ruleIds);
}