package com.sinosoft.aiqc.db.dao;

import com.sinosoft.aiqc.db.domain.YyzjSHotwordNum;
import com.sinosoft.aiqc.db.domain.YyzjSHotwordNumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YyzjSHotwordNumMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_hotword_num
     *
     * @mbg.generated
     */
    long countByExample(YyzjSHotwordNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_hotword_num
     *
     * @mbg.generated
     */
    int deleteByExample(YyzjSHotwordNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_hotword_num
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String hotWordNumId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_hotword_num
     *
     * @mbg.generated
     */
    int insert(YyzjSHotwordNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_hotword_num
     *
     * @mbg.generated
     */
    int insertSelective(YyzjSHotwordNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_hotword_num
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjSHotwordNum selectOneByExample(YyzjSHotwordNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_hotword_num
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjSHotwordNum selectOneByExampleSelective(@Param("example") YyzjSHotwordNumExample example, @Param("selective") YyzjSHotwordNum.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_hotword_num
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YyzjSHotwordNum> selectByExampleSelective(@Param("example") YyzjSHotwordNumExample example, @Param("selective") YyzjSHotwordNum.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_hotword_num
     *
     * @mbg.generated
     */
    List<YyzjSHotwordNum> selectByExample(YyzjSHotwordNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_hotword_num
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjSHotwordNum selectByPrimaryKeySelective(@Param("hotWordNumId") String hotWordNumId, @Param("selective") YyzjSHotwordNum.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_hotword_num
     *
     * @mbg.generated
     */
    YyzjSHotwordNum selectByPrimaryKey(String hotWordNumId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_hotword_num
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YyzjSHotwordNum record, @Param("example") YyzjSHotwordNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_hotword_num
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YyzjSHotwordNum record, @Param("example") YyzjSHotwordNumExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_hotword_num
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YyzjSHotwordNum record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_hotword_num
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YyzjSHotwordNum record);
}