package com.sinosoft.aiqc.db.dao;

import com.sinosoft.aiqc.db.domain.YyzjCEngine;
import com.sinosoft.aiqc.db.domain.YyzjCEngineExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YyzjCEngineMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_engine
     *
     * @mbg.generated
     */
    long countByExample(YyzjCEngineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_engine
     *
     * @mbg.generated
     */
    int deleteByExample(YyzjCEngineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_engine
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String engineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_engine
     *
     * @mbg.generated
     */
    int insert(YyzjCEngine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_engine
     *
     * @mbg.generated
     */
    int insertSelective(YyzjCEngine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_engine
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjCEngine selectOneByExample(YyzjCEngineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_engine
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjCEngine selectOneByExampleSelective(@Param("example") YyzjCEngineExample example, @Param("selective") YyzjCEngine.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_engine
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YyzjCEngine> selectByExampleSelective(@Param("example") YyzjCEngineExample example, @Param("selective") YyzjCEngine.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_engine
     *
     * @mbg.generated
     */
    List<YyzjCEngine> selectByExample(YyzjCEngineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_engine
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjCEngine selectByPrimaryKeySelective(@Param("engineId") String engineId, @Param("selective") YyzjCEngine.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_engine
     *
     * @mbg.generated
     */
    YyzjCEngine selectByPrimaryKey(String engineId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_engine
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YyzjCEngine record, @Param("example") YyzjCEngineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_engine
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YyzjCEngine record, @Param("example") YyzjCEngineExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_engine
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YyzjCEngine record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_engine
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YyzjCEngine record);
}