package com.sinosoft.aiqc.db.dao;

import com.sinosoft.aiqc.db.domain.YyzjTScoreTotalData20181114;
import com.sinosoft.aiqc.db.domain.YyzjTScoreTotalData20181114Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YyzjTScoreTotalData20181114Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181114
     *
     * @mbg.generated
     */
    long countByExample(YyzjTScoreTotalData20181114Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181114
     *
     * @mbg.generated
     */
    int deleteByExample(YyzjTScoreTotalData20181114Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181114
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String scoreTotalDataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181114
     *
     * @mbg.generated
     */
    int insert(YyzjTScoreTotalData20181114 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181114
     *
     * @mbg.generated
     */
    int insertSelective(YyzjTScoreTotalData20181114 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181114
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjTScoreTotalData20181114 selectOneByExample(YyzjTScoreTotalData20181114Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181114
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjTScoreTotalData20181114 selectOneByExampleSelective(@Param("example") YyzjTScoreTotalData20181114Example example, @Param("selective") YyzjTScoreTotalData20181114.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181114
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjTScoreTotalData20181114 selectOneByExampleWithBLOBs(YyzjTScoreTotalData20181114Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181114
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YyzjTScoreTotalData20181114> selectByExampleSelective(@Param("example") YyzjTScoreTotalData20181114Example example, @Param("selective") YyzjTScoreTotalData20181114.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181114
     *
     * @mbg.generated
     */
    List<YyzjTScoreTotalData20181114> selectByExampleWithBLOBs(YyzjTScoreTotalData20181114Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181114
     *
     * @mbg.generated
     */
    List<YyzjTScoreTotalData20181114> selectByExample(YyzjTScoreTotalData20181114Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181114
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjTScoreTotalData20181114 selectByPrimaryKeySelective(@Param("scoreTotalDataId") String scoreTotalDataId, @Param("selective") YyzjTScoreTotalData20181114.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181114
     *
     * @mbg.generated
     */
    YyzjTScoreTotalData20181114 selectByPrimaryKey(String scoreTotalDataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181114
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YyzjTScoreTotalData20181114 record, @Param("example") YyzjTScoreTotalData20181114Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181114
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") YyzjTScoreTotalData20181114 record, @Param("example") YyzjTScoreTotalData20181114Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181114
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YyzjTScoreTotalData20181114 record, @Param("example") YyzjTScoreTotalData20181114Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181114
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YyzjTScoreTotalData20181114 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181114
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(YyzjTScoreTotalData20181114 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181114
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YyzjTScoreTotalData20181114 record);
}