package com.sinosoft.aiqc.db.dao;

import com.sinosoft.aiqc.db.domain.YyzjCProducerEleValue;
import com.sinosoft.aiqc.db.domain.YyzjCProducerEleValueExample;
import java.util.List;

import com.sinosoft.aiqc.db.domain.extend.YyzjCProducerEleValueExt;
import org.apache.ibatis.annotations.Param;

public interface YyzjCProducerEleValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_value
     *
     * @mbg.generated
     */
    long countByExample(YyzjCProducerEleValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_value
     *
     * @mbg.generated
     */
    int deleteByExample(YyzjCProducerEleValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_value
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String eleValueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_value
     *
     * @mbg.generated
     */
    int insert(YyzjCProducerEleValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_value
     *
     * @mbg.generated
     */
    int insertSelective(YyzjCProducerEleValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_value
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjCProducerEleValue selectOneByExample(YyzjCProducerEleValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_value
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjCProducerEleValue selectOneByExampleSelective(@Param("example") YyzjCProducerEleValueExample example, @Param("selective") YyzjCProducerEleValue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_value
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YyzjCProducerEleValue> selectByExampleSelective(@Param("example") YyzjCProducerEleValueExample example, @Param("selective") YyzjCProducerEleValue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_value
     *
     * @mbg.generated
     */
    List<YyzjCProducerEleValue> selectByExample(YyzjCProducerEleValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_value
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjCProducerEleValue selectByPrimaryKeySelective(@Param("eleValueId") String eleValueId, @Param("selective") YyzjCProducerEleValue.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_value
     *
     * @mbg.generated
     */
    YyzjCProducerEleValue selectByPrimaryKey(String eleValueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_value
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YyzjCProducerEleValue record, @Param("example") YyzjCProducerEleValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_value
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YyzjCProducerEleValue record, @Param("example") YyzjCProducerEleValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YyzjCProducerEleValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_producer_ele_value
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YyzjCProducerEleValue record);


    List<YyzjCProducerEleValueExt> getProducerEleValueExt(String ruleId);
}