package com.sinosoft.aiqc.db.dao;

import com.sinosoft.aiqc.db.domain.YyzjSStatisticsStatus;
import com.sinosoft.aiqc.db.domain.YyzjSStatisticsStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YyzjSStatisticsStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_statistics_status
     *
     * @mbg.generated
     */
    long countByExample(YyzjSStatisticsStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_statistics_status
     *
     * @mbg.generated
     */
    int deleteByExample(YyzjSStatisticsStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_statistics_status
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String statusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_statistics_status
     *
     * @mbg.generated
     */
    int insert(YyzjSStatisticsStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_statistics_status
     *
     * @mbg.generated
     */
    int insertSelective(YyzjSStatisticsStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_statistics_status
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjSStatisticsStatus selectOneByExample(YyzjSStatisticsStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_statistics_status
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjSStatisticsStatus selectOneByExampleSelective(@Param("example") YyzjSStatisticsStatusExample example, @Param("selective") YyzjSStatisticsStatus.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_statistics_status
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YyzjSStatisticsStatus> selectByExampleSelective(@Param("example") YyzjSStatisticsStatusExample example, @Param("selective") YyzjSStatisticsStatus.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_statistics_status
     *
     * @mbg.generated
     */
    List<YyzjSStatisticsStatus> selectByExample(YyzjSStatisticsStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_statistics_status
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjSStatisticsStatus selectByPrimaryKeySelective(@Param("statusId") String statusId, @Param("selective") YyzjSStatisticsStatus.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_statistics_status
     *
     * @mbg.generated
     */
    YyzjSStatisticsStatus selectByPrimaryKey(String statusId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_statistics_status
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YyzjSStatisticsStatus record, @Param("example") YyzjSStatisticsStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_statistics_status
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YyzjSStatisticsStatus record, @Param("example") YyzjSStatisticsStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_statistics_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YyzjSStatisticsStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_s_statistics_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YyzjSStatisticsStatus record);
}