package com.sinosoft.aiqc.db.dao;

import com.sinosoft.aiqc.db.domain.YyzjTScoreTotalData20181109;
import com.sinosoft.aiqc.db.domain.YyzjTScoreTotalData20181109Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YyzjTScoreTotalData20181109Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181109
     *
     * @mbg.generated
     */
    long countByExample(YyzjTScoreTotalData20181109Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181109
     *
     * @mbg.generated
     */
    int deleteByExample(YyzjTScoreTotalData20181109Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181109
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String scoreTotalDataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181109
     *
     * @mbg.generated
     */
    int insert(YyzjTScoreTotalData20181109 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181109
     *
     * @mbg.generated
     */
    int insertSelective(YyzjTScoreTotalData20181109 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181109
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjTScoreTotalData20181109 selectOneByExample(YyzjTScoreTotalData20181109Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181109
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjTScoreTotalData20181109 selectOneByExampleSelective(@Param("example") YyzjTScoreTotalData20181109Example example, @Param("selective") YyzjTScoreTotalData20181109.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181109
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjTScoreTotalData20181109 selectOneByExampleWithBLOBs(YyzjTScoreTotalData20181109Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181109
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YyzjTScoreTotalData20181109> selectByExampleSelective(@Param("example") YyzjTScoreTotalData20181109Example example, @Param("selective") YyzjTScoreTotalData20181109.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181109
     *
     * @mbg.generated
     */
    List<YyzjTScoreTotalData20181109> selectByExampleWithBLOBs(YyzjTScoreTotalData20181109Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181109
     *
     * @mbg.generated
     */
    List<YyzjTScoreTotalData20181109> selectByExample(YyzjTScoreTotalData20181109Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181109
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjTScoreTotalData20181109 selectByPrimaryKeySelective(@Param("scoreTotalDataId") String scoreTotalDataId, @Param("selective") YyzjTScoreTotalData20181109.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181109
     *
     * @mbg.generated
     */
    YyzjTScoreTotalData20181109 selectByPrimaryKey(String scoreTotalDataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181109
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YyzjTScoreTotalData20181109 record, @Param("example") YyzjTScoreTotalData20181109Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181109
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") YyzjTScoreTotalData20181109 record, @Param("example") YyzjTScoreTotalData20181109Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181109
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YyzjTScoreTotalData20181109 record, @Param("example") YyzjTScoreTotalData20181109Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181109
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YyzjTScoreTotalData20181109 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181109
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(YyzjTScoreTotalData20181109 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181109
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YyzjTScoreTotalData20181109 record);
}