package com.sinosoft.aiqc.db.dao;

import com.sinosoft.aiqc.db.domain.YyzjTScoreTotalData20181203;
import com.sinosoft.aiqc.db.domain.YyzjTScoreTotalData20181203Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YyzjTScoreTotalData20181203Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181203
     *
     * @mbg.generated
     */
    long countByExample(YyzjTScoreTotalData20181203Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181203
     *
     * @mbg.generated
     */
    int deleteByExample(YyzjTScoreTotalData20181203Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181203
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String scoreTotalDataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181203
     *
     * @mbg.generated
     */
    int insert(YyzjTScoreTotalData20181203 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181203
     *
     * @mbg.generated
     */
    int insertSelective(YyzjTScoreTotalData20181203 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181203
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjTScoreTotalData20181203 selectOneByExample(YyzjTScoreTotalData20181203Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181203
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjTScoreTotalData20181203 selectOneByExampleSelective(@Param("example") YyzjTScoreTotalData20181203Example example, @Param("selective") YyzjTScoreTotalData20181203.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181203
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjTScoreTotalData20181203 selectOneByExampleWithBLOBs(YyzjTScoreTotalData20181203Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181203
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YyzjTScoreTotalData20181203> selectByExampleSelective(@Param("example") YyzjTScoreTotalData20181203Example example, @Param("selective") YyzjTScoreTotalData20181203.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181203
     *
     * @mbg.generated
     */
    List<YyzjTScoreTotalData20181203> selectByExampleWithBLOBs(YyzjTScoreTotalData20181203Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181203
     *
     * @mbg.generated
     */
    List<YyzjTScoreTotalData20181203> selectByExample(YyzjTScoreTotalData20181203Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181203
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjTScoreTotalData20181203 selectByPrimaryKeySelective(@Param("scoreTotalDataId") String scoreTotalDataId, @Param("selective") YyzjTScoreTotalData20181203.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181203
     *
     * @mbg.generated
     */
    YyzjTScoreTotalData20181203 selectByPrimaryKey(String scoreTotalDataId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181203
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YyzjTScoreTotalData20181203 record, @Param("example") YyzjTScoreTotalData20181203Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181203
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") YyzjTScoreTotalData20181203 record, @Param("example") YyzjTScoreTotalData20181203Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181203
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YyzjTScoreTotalData20181203 record, @Param("example") YyzjTScoreTotalData20181203Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181203
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YyzjTScoreTotalData20181203 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181203
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(YyzjTScoreTotalData20181203 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_score_total_data_20181203
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YyzjTScoreTotalData20181203 record);
}