package com.sinosoft.aiqc.db.dao;

import com.sinosoft.aiqc.db.domain.YyzjLEngineLog;
import com.sinosoft.aiqc.db.domain.YyzjLEngineLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YyzjLEngineLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_l_engine_log
     *
     * @mbg.generated
     */
    long countByExample(YyzjLEngineLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_l_engine_log
     *
     * @mbg.generated
     */
    int deleteByExample(YyzjLEngineLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_l_engine_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_l_engine_log
     *
     * @mbg.generated
     */
    int insert(YyzjLEngineLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_l_engine_log
     *
     * @mbg.generated
     */
    int insertSelective(YyzjLEngineLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_l_engine_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjLEngineLog selectOneByExample(YyzjLEngineLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_l_engine_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjLEngineLog selectOneByExampleSelective(@Param("example") YyzjLEngineLogExample example, @Param("selective") YyzjLEngineLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_l_engine_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<YyzjLEngineLog> selectByExampleSelective(@Param("example") YyzjLEngineLogExample example, @Param("selective") YyzjLEngineLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_l_engine_log
     *
     * @mbg.generated
     */
    List<YyzjLEngineLog> selectByExample(YyzjLEngineLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_l_engine_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    YyzjLEngineLog selectByPrimaryKeySelective(@Param("logId") String logId, @Param("selective") YyzjLEngineLog.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_l_engine_log
     *
     * @mbg.generated
     */
    YyzjLEngineLog selectByPrimaryKey(String logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_l_engine_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YyzjLEngineLog record, @Param("example") YyzjLEngineLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_l_engine_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YyzjLEngineLog record, @Param("example") YyzjLEngineLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_l_engine_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YyzjLEngineLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_l_engine_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YyzjLEngineLog record);
}