spring:
  profiles:
    active: db, core, zj
  messages:
    encoding: UTF-8

server:
  port: 8082

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    com.sinosoft.aiqc.wx:  DEBUG
    com.sinosoft.aiqc:  ERROR