spring:
  profiles:
    active: db, core, zj
  messages:
    encoding: UTF-8

server:
  port: 8082

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    com.sinosoft.aiqc.wx:  DEBUG
    com.sinosoft.aiqc:  ERROR


yyzj:
  analyze:
    web:
      path: http://localhost:8080/analyze/


engine:
  analyze:
    save:
      source: false
      word: false
      rule:
        exec:
          result:
            ele: false
    class:
      loader:
        url: E:/workspace/HYTX/analyze/target/znyyzj_analyze/WEB-INF/classes

zj:
  uploadAudio:
    path: E:/workspace/HYTX/analyze/target/znyyzj_analyze/WEB-INF/classes
  mount:
    root:
      path: E:/workspace/HYTX/analyze/target/znyyzj_analyze/WEB-INF/classes