package com.sinosoft.aiqc.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class YyzjTQualityUserYyyymm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyzj_t_quality_user_yyyymm.report_id
     *
     * @mbg.generated
     */
    private String reportId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyzj_t_quality_user_yyyymm.audio_code
     *
     * @mbg.generated
     */
    private String audioCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyzj_t_quality_user_yyyymm.base_id
     *
     * @mbg.generated
     */
    private String baseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyzj_t_quality_user_yyyymm.score_total_data_id
     *
     * @mbg.generated
     */
    private String scoreTotalDataId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyzj_t_quality_user_yyyymm.score_detail_data_id
     *
     * @mbg.generated
     */
    private String scoreDetailDataId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyzj_t_quality_user_yyyymm.total_score_id
     *
     * @mbg.generated
     */
    private String totalScoreId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyzj_t_quality_user_yyyymm.detail_score_id
     *
     * @mbg.generated
     */
    private String detailScoreId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyzj_t_quality_user_yyyymm.assign_log_id
     *
     * @mbg.generated
     */
    private String assignLogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyzj_t_quality_user_yyyymm.quality_user
     *
     * @mbg.generated
     */
    private String qualityUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyzj_t_quality_user_yyyymm.quality_date
     *
     * @mbg.generated
     */
    private LocalDateTime qualityDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyzj_t_quality_user_yyyymm.process_result
     *
     * @mbg.generated
     */
    private String processResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyzj_t_quality_user_yyyymm.sys_id
     *
     * @mbg.generated
     */
    private String sysId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyzj_t_quality_user_yyyymm.result_type
     *
     * @mbg.generated
     */
    private String resultType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyzj_t_quality_user_yyyymm.report_id
     *
     * @return the value of yyzj_t_quality_user_yyyymm.report_id
     *
     * @mbg.generated
     */
    public String getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyzj_t_quality_user_yyyymm.report_id
     *
     * @param reportId the value for yyzj_t_quality_user_yyyymm.report_id
     *
     * @mbg.generated
     */
    public void setReportId(String reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyzj_t_quality_user_yyyymm.audio_code
     *
     * @return the value of yyzj_t_quality_user_yyyymm.audio_code
     *
     * @mbg.generated
     */
    public String getAudioCode() {
        return audioCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyzj_t_quality_user_yyyymm.audio_code
     *
     * @param audioCode the value for yyzj_t_quality_user_yyyymm.audio_code
     *
     * @mbg.generated
     */
    public void setAudioCode(String audioCode) {
        this.audioCode = audioCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyzj_t_quality_user_yyyymm.base_id
     *
     * @return the value of yyzj_t_quality_user_yyyymm.base_id
     *
     * @mbg.generated
     */
    public String getBaseId() {
        return baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyzj_t_quality_user_yyyymm.base_id
     *
     * @param baseId the value for yyzj_t_quality_user_yyyymm.base_id
     *
     * @mbg.generated
     */
    public void setBaseId(String baseId) {
        this.baseId = baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyzj_t_quality_user_yyyymm.score_total_data_id
     *
     * @return the value of yyzj_t_quality_user_yyyymm.score_total_data_id
     *
     * @mbg.generated
     */
    public String getScoreTotalDataId() {
        return scoreTotalDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyzj_t_quality_user_yyyymm.score_total_data_id
     *
     * @param scoreTotalDataId the value for yyzj_t_quality_user_yyyymm.score_total_data_id
     *
     * @mbg.generated
     */
    public void setScoreTotalDataId(String scoreTotalDataId) {
        this.scoreTotalDataId = scoreTotalDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyzj_t_quality_user_yyyymm.score_detail_data_id
     *
     * @return the value of yyzj_t_quality_user_yyyymm.score_detail_data_id
     *
     * @mbg.generated
     */
    public String getScoreDetailDataId() {
        return scoreDetailDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyzj_t_quality_user_yyyymm.score_detail_data_id
     *
     * @param scoreDetailDataId the value for yyzj_t_quality_user_yyyymm.score_detail_data_id
     *
     * @mbg.generated
     */
    public void setScoreDetailDataId(String scoreDetailDataId) {
        this.scoreDetailDataId = scoreDetailDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyzj_t_quality_user_yyyymm.total_score_id
     *
     * @return the value of yyzj_t_quality_user_yyyymm.total_score_id
     *
     * @mbg.generated
     */
    public String getTotalScoreId() {
        return totalScoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyzj_t_quality_user_yyyymm.total_score_id
     *
     * @param totalScoreId the value for yyzj_t_quality_user_yyyymm.total_score_id
     *
     * @mbg.generated
     */
    public void setTotalScoreId(String totalScoreId) {
        this.totalScoreId = totalScoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyzj_t_quality_user_yyyymm.detail_score_id
     *
     * @return the value of yyzj_t_quality_user_yyyymm.detail_score_id
     *
     * @mbg.generated
     */
    public String getDetailScoreId() {
        return detailScoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyzj_t_quality_user_yyyymm.detail_score_id
     *
     * @param detailScoreId the value for yyzj_t_quality_user_yyyymm.detail_score_id
     *
     * @mbg.generated
     */
    public void setDetailScoreId(String detailScoreId) {
        this.detailScoreId = detailScoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyzj_t_quality_user_yyyymm.assign_log_id
     *
     * @return the value of yyzj_t_quality_user_yyyymm.assign_log_id
     *
     * @mbg.generated
     */
    public String getAssignLogId() {
        return assignLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyzj_t_quality_user_yyyymm.assign_log_id
     *
     * @param assignLogId the value for yyzj_t_quality_user_yyyymm.assign_log_id
     *
     * @mbg.generated
     */
    public void setAssignLogId(String assignLogId) {
        this.assignLogId = assignLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyzj_t_quality_user_yyyymm.quality_user
     *
     * @return the value of yyzj_t_quality_user_yyyymm.quality_user
     *
     * @mbg.generated
     */
    public String getQualityUser() {
        return qualityUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyzj_t_quality_user_yyyymm.quality_user
     *
     * @param qualityUser the value for yyzj_t_quality_user_yyyymm.quality_user
     *
     * @mbg.generated
     */
    public void setQualityUser(String qualityUser) {
        this.qualityUser = qualityUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyzj_t_quality_user_yyyymm.quality_date
     *
     * @return the value of yyzj_t_quality_user_yyyymm.quality_date
     *
     * @mbg.generated
     */
    public LocalDateTime getQualityDate() {
        return qualityDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyzj_t_quality_user_yyyymm.quality_date
     *
     * @param qualityDate the value for yyzj_t_quality_user_yyyymm.quality_date
     *
     * @mbg.generated
     */
    public void setQualityDate(LocalDateTime qualityDate) {
        this.qualityDate = qualityDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyzj_t_quality_user_yyyymm.process_result
     *
     * @return the value of yyzj_t_quality_user_yyyymm.process_result
     *
     * @mbg.generated
     */
    public String getProcessResult() {
        return processResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyzj_t_quality_user_yyyymm.process_result
     *
     * @param processResult the value for yyzj_t_quality_user_yyyymm.process_result
     *
     * @mbg.generated
     */
    public void setProcessResult(String processResult) {
        this.processResult = processResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyzj_t_quality_user_yyyymm.sys_id
     *
     * @return the value of yyzj_t_quality_user_yyyymm.sys_id
     *
     * @mbg.generated
     */
    public String getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyzj_t_quality_user_yyyymm.sys_id
     *
     * @param sysId the value for yyzj_t_quality_user_yyyymm.sys_id
     *
     * @mbg.generated
     */
    public void setSysId(String sysId) {
        this.sysId = sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyzj_t_quality_user_yyyymm.result_type
     *
     * @return the value of yyzj_t_quality_user_yyyymm.result_type
     *
     * @mbg.generated
     */
    public String getResultType() {
        return resultType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyzj_t_quality_user_yyyymm.result_type
     *
     * @param resultType the value for yyzj_t_quality_user_yyyymm.result_type
     *
     * @mbg.generated
     */
    public void setResultType(String resultType) {
        this.resultType = resultType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_quality_user_yyyymm
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", reportId=").append(reportId);
        sb.append(", audioCode=").append(audioCode);
        sb.append(", baseId=").append(baseId);
        sb.append(", scoreTotalDataId=").append(scoreTotalDataId);
        sb.append(", scoreDetailDataId=").append(scoreDetailDataId);
        sb.append(", totalScoreId=").append(totalScoreId);
        sb.append(", detailScoreId=").append(detailScoreId);
        sb.append(", assignLogId=").append(assignLogId);
        sb.append(", qualityUser=").append(qualityUser);
        sb.append(", qualityDate=").append(qualityDate);
        sb.append(", processResult=").append(processResult);
        sb.append(", sysId=").append(sysId);
        sb.append(", resultType=").append(resultType);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_quality_user_yyyymm
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        YyzjTQualityUserYyyymm other = (YyzjTQualityUserYyyymm) that;
        return (this.getReportId() == null ? other.getReportId() == null : this.getReportId().equals(other.getReportId()))
            && (this.getAudioCode() == null ? other.getAudioCode() == null : this.getAudioCode().equals(other.getAudioCode()))
            && (this.getBaseId() == null ? other.getBaseId() == null : this.getBaseId().equals(other.getBaseId()))
            && (this.getScoreTotalDataId() == null ? other.getScoreTotalDataId() == null : this.getScoreTotalDataId().equals(other.getScoreTotalDataId()))
            && (this.getScoreDetailDataId() == null ? other.getScoreDetailDataId() == null : this.getScoreDetailDataId().equals(other.getScoreDetailDataId()))
            && (this.getTotalScoreId() == null ? other.getTotalScoreId() == null : this.getTotalScoreId().equals(other.getTotalScoreId()))
            && (this.getDetailScoreId() == null ? other.getDetailScoreId() == null : this.getDetailScoreId().equals(other.getDetailScoreId()))
            && (this.getAssignLogId() == null ? other.getAssignLogId() == null : this.getAssignLogId().equals(other.getAssignLogId()))
            && (this.getQualityUser() == null ? other.getQualityUser() == null : this.getQualityUser().equals(other.getQualityUser()))
            && (this.getQualityDate() == null ? other.getQualityDate() == null : this.getQualityDate().equals(other.getQualityDate()))
            && (this.getProcessResult() == null ? other.getProcessResult() == null : this.getProcessResult().equals(other.getProcessResult()))
            && (this.getSysId() == null ? other.getSysId() == null : this.getSysId().equals(other.getSysId()))
            && (this.getResultType() == null ? other.getResultType() == null : this.getResultType().equals(other.getResultType()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_t_quality_user_yyyymm
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getReportId() == null) ? 0 : getReportId().hashCode());
        result = prime * result + ((getAudioCode() == null) ? 0 : getAudioCode().hashCode());
        result = prime * result + ((getBaseId() == null) ? 0 : getBaseId().hashCode());
        result = prime * result + ((getScoreTotalDataId() == null) ? 0 : getScoreTotalDataId().hashCode());
        result = prime * result + ((getScoreDetailDataId() == null) ? 0 : getScoreDetailDataId().hashCode());
        result = prime * result + ((getTotalScoreId() == null) ? 0 : getTotalScoreId().hashCode());
        result = prime * result + ((getDetailScoreId() == null) ? 0 : getDetailScoreId().hashCode());
        result = prime * result + ((getAssignLogId() == null) ? 0 : getAssignLogId().hashCode());
        result = prime * result + ((getQualityUser() == null) ? 0 : getQualityUser().hashCode());
        result = prime * result + ((getQualityDate() == null) ? 0 : getQualityDate().hashCode());
        result = prime * result + ((getProcessResult() == null) ? 0 : getProcessResult().hashCode());
        result = prime * result + ((getSysId() == null) ? 0 : getSysId().hashCode());
        result = prime * result + ((getResultType() == null) ? 0 : getResultType().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table yyzj_t_quality_user_yyyymm
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        reportId("report_id", "reportId", "CHAR", false),
        audioCode("audio_code", "audioCode", "VARCHAR", false),
        baseId("base_id", "baseId", "VARCHAR", false),
        scoreTotalDataId("score_total_data_id", "scoreTotalDataId", "VARCHAR", false),
        scoreDetailDataId("score_detail_data_id", "scoreDetailDataId", "VARCHAR", false),
        totalScoreId("total_score_id", "totalScoreId", "CHAR", false),
        detailScoreId("detail_score_id", "detailScoreId", "CHAR", false),
        assignLogId("assign_log_id", "assignLogId", "VARCHAR", false),
        qualityUser("quality_user", "qualityUser", "VARCHAR", false),
        qualityDate("quality_date", "qualityDate", "TIMESTAMP", false),
        processResult("process_result", "processResult", "VARCHAR", false),
        sysId("sys_id", "sysId", "CHAR", false),
        resultType("result_type", "resultType", "CHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yyzj_t_quality_user_yyyymm
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yyzj_t_quality_user_yyyymm
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yyzj_t_quality_user_yyyymm
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yyzj_t_quality_user_yyyymm
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yyzj_t_quality_user_yyyymm
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yyzj_t_quality_user_yyyymm
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_t_quality_user_yyyymm
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_t_quality_user_yyyymm
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_t_quality_user_yyyymm
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_t_quality_user_yyyymm
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_t_quality_user_yyyymm
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_t_quality_user_yyyymm
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_t_quality_user_yyyymm
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_t_quality_user_yyyymm
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_t_quality_user_yyyymm
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}