package com.sinosoft.aiqc.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class YyzjCAssignTaskExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yyzj_c_assign_task
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yyzj_c_assign_task
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yyzj_c_assign_task
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_assign_task
     *
     * @mbg.generated
     */
    public YyzjCAssignTaskExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_assign_task
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_assign_task
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_assign_task
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_assign_task
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_assign_task
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_assign_task
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_assign_task
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_assign_task
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public YyzjCAssignTaskExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_assign_task
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public YyzjCAssignTaskExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_assign_task
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_assign_task
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_assign_task
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_assign_task
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Criteria newAndCreateCriteria() {
        YyzjCAssignTaskExample example = new YyzjCAssignTaskExample();
        return example.createCriteria();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yyzj_c_assign_task
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("task_id is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("task_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(String value) {
            addCriterion("task_id =", value, "taskId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTaskIdEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("task_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(String value) {
            addCriterion("task_id <>", value, "taskId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTaskIdNotEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("task_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(String value) {
            addCriterion("task_id >", value, "taskId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTaskIdGreaterThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("task_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(String value) {
            addCriterion("task_id >=", value, "taskId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTaskIdGreaterThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("task_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(String value) {
            addCriterion("task_id <", value, "taskId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTaskIdLessThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("task_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(String value) {
            addCriterion("task_id <=", value, "taskId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTaskIdLessThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("task_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTaskIdLike(String value) {
            addCriterion("task_id like", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotLike(String value) {
            addCriterion("task_id not like", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<String> values) {
            addCriterion("task_id in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<String> values) {
            addCriterion("task_id not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(String value1, String value2) {
            addCriterion("task_id between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(String value1, String value2) {
            addCriterion("task_id not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andSysIdIsNull() {
            addCriterion("sys_id is null");
            return (Criteria) this;
        }

        public Criteria andSysIdIsNotNull() {
            addCriterion("sys_id is not null");
            return (Criteria) this;
        }

        public Criteria andSysIdEqualTo(String value) {
            addCriterion("sys_id =", value, "sysId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSysIdEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("sys_id = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSysIdNotEqualTo(String value) {
            addCriterion("sys_id <>", value, "sysId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSysIdNotEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("sys_id <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSysIdGreaterThan(String value) {
            addCriterion("sys_id >", value, "sysId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSysIdGreaterThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("sys_id > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSysIdGreaterThanOrEqualTo(String value) {
            addCriterion("sys_id >=", value, "sysId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSysIdGreaterThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("sys_id >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSysIdLessThan(String value) {
            addCriterion("sys_id <", value, "sysId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSysIdLessThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("sys_id < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSysIdLessThanOrEqualTo(String value) {
            addCriterion("sys_id <=", value, "sysId");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andSysIdLessThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("sys_id <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andSysIdLike(String value) {
            addCriterion("sys_id like", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdNotLike(String value) {
            addCriterion("sys_id not like", value, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdIn(List<String> values) {
            addCriterion("sys_id in", values, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdNotIn(List<String> values) {
            addCriterion("sys_id not in", values, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdBetween(String value1, String value2) {
            addCriterion("sys_id between", value1, value2, "sysId");
            return (Criteria) this;
        }

        public Criteria andSysIdNotBetween(String value1, String value2) {
            addCriterion("sys_id not between", value1, value2, "sysId");
            return (Criteria) this;
        }

        public Criteria andCondStartTimeIsNull() {
            addCriterion("cond_start_time is null");
            return (Criteria) this;
        }

        public Criteria andCondStartTimeIsNotNull() {
            addCriterion("cond_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andCondStartTimeEqualTo(LocalDateTime value) {
            addCriterion("cond_start_time =", value, "condStartTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondStartTimeEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_start_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondStartTimeNotEqualTo(LocalDateTime value) {
            addCriterion("cond_start_time <>", value, "condStartTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondStartTimeNotEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_start_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondStartTimeGreaterThan(LocalDateTime value) {
            addCriterion("cond_start_time >", value, "condStartTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondStartTimeGreaterThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_start_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondStartTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("cond_start_time >=", value, "condStartTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondStartTimeGreaterThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_start_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondStartTimeLessThan(LocalDateTime value) {
            addCriterion("cond_start_time <", value, "condStartTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondStartTimeLessThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_start_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondStartTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("cond_start_time <=", value, "condStartTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondStartTimeLessThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_start_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondStartTimeIn(List<LocalDateTime> values) {
            addCriterion("cond_start_time in", values, "condStartTime");
            return (Criteria) this;
        }

        public Criteria andCondStartTimeNotIn(List<LocalDateTime> values) {
            addCriterion("cond_start_time not in", values, "condStartTime");
            return (Criteria) this;
        }

        public Criteria andCondStartTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("cond_start_time between", value1, value2, "condStartTime");
            return (Criteria) this;
        }

        public Criteria andCondStartTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("cond_start_time not between", value1, value2, "condStartTime");
            return (Criteria) this;
        }

        public Criteria andCondEndTimeIsNull() {
            addCriterion("cond_end_time is null");
            return (Criteria) this;
        }

        public Criteria andCondEndTimeIsNotNull() {
            addCriterion("cond_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andCondEndTimeEqualTo(LocalDateTime value) {
            addCriterion("cond_end_time =", value, "condEndTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondEndTimeEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_end_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondEndTimeNotEqualTo(LocalDateTime value) {
            addCriterion("cond_end_time <>", value, "condEndTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondEndTimeNotEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_end_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondEndTimeGreaterThan(LocalDateTime value) {
            addCriterion("cond_end_time >", value, "condEndTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondEndTimeGreaterThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_end_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondEndTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("cond_end_time >=", value, "condEndTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondEndTimeGreaterThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_end_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondEndTimeLessThan(LocalDateTime value) {
            addCriterion("cond_end_time <", value, "condEndTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondEndTimeLessThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_end_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondEndTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("cond_end_time <=", value, "condEndTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondEndTimeLessThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_end_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondEndTimeIn(List<LocalDateTime> values) {
            addCriterion("cond_end_time in", values, "condEndTime");
            return (Criteria) this;
        }

        public Criteria andCondEndTimeNotIn(List<LocalDateTime> values) {
            addCriterion("cond_end_time not in", values, "condEndTime");
            return (Criteria) this;
        }

        public Criteria andCondEndTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("cond_end_time between", value1, value2, "condEndTime");
            return (Criteria) this;
        }

        public Criteria andCondEndTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("cond_end_time not between", value1, value2, "condEndTime");
            return (Criteria) this;
        }

        public Criteria andCondCustomerIsNull() {
            addCriterion("cond_customer is null");
            return (Criteria) this;
        }

        public Criteria andCondCustomerIsNotNull() {
            addCriterion("cond_customer is not null");
            return (Criteria) this;
        }

        public Criteria andCondCustomerEqualTo(String value) {
            addCriterion("cond_customer =", value, "condCustomer");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondCustomerEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_customer = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondCustomerNotEqualTo(String value) {
            addCriterion("cond_customer <>", value, "condCustomer");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondCustomerNotEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_customer <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondCustomerGreaterThan(String value) {
            addCriterion("cond_customer >", value, "condCustomer");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondCustomerGreaterThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_customer > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondCustomerGreaterThanOrEqualTo(String value) {
            addCriterion("cond_customer >=", value, "condCustomer");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondCustomerGreaterThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_customer >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondCustomerLessThan(String value) {
            addCriterion("cond_customer <", value, "condCustomer");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondCustomerLessThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_customer < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondCustomerLessThanOrEqualTo(String value) {
            addCriterion("cond_customer <=", value, "condCustomer");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondCustomerLessThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_customer <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondCustomerLike(String value) {
            addCriterion("cond_customer like", value, "condCustomer");
            return (Criteria) this;
        }

        public Criteria andCondCustomerNotLike(String value) {
            addCriterion("cond_customer not like", value, "condCustomer");
            return (Criteria) this;
        }

        public Criteria andCondCustomerIn(List<String> values) {
            addCriterion("cond_customer in", values, "condCustomer");
            return (Criteria) this;
        }

        public Criteria andCondCustomerNotIn(List<String> values) {
            addCriterion("cond_customer not in", values, "condCustomer");
            return (Criteria) this;
        }

        public Criteria andCondCustomerBetween(String value1, String value2) {
            addCriterion("cond_customer between", value1, value2, "condCustomer");
            return (Criteria) this;
        }

        public Criteria andCondCustomerNotBetween(String value1, String value2) {
            addCriterion("cond_customer not between", value1, value2, "condCustomer");
            return (Criteria) this;
        }

        public Criteria andCondDurtimeIsNull() {
            addCriterion("cond_durtime is null");
            return (Criteria) this;
        }

        public Criteria andCondDurtimeIsNotNull() {
            addCriterion("cond_durtime is not null");
            return (Criteria) this;
        }

        public Criteria andCondDurtimeEqualTo(String value) {
            addCriterion("cond_durtime =", value, "condDurtime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondDurtimeEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_durtime = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondDurtimeNotEqualTo(String value) {
            addCriterion("cond_durtime <>", value, "condDurtime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondDurtimeNotEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_durtime <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondDurtimeGreaterThan(String value) {
            addCriterion("cond_durtime >", value, "condDurtime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondDurtimeGreaterThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_durtime > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondDurtimeGreaterThanOrEqualTo(String value) {
            addCriterion("cond_durtime >=", value, "condDurtime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondDurtimeGreaterThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_durtime >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondDurtimeLessThan(String value) {
            addCriterion("cond_durtime <", value, "condDurtime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondDurtimeLessThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_durtime < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondDurtimeLessThanOrEqualTo(String value) {
            addCriterion("cond_durtime <=", value, "condDurtime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondDurtimeLessThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_durtime <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondDurtimeLike(String value) {
            addCriterion("cond_durtime like", value, "condDurtime");
            return (Criteria) this;
        }

        public Criteria andCondDurtimeNotLike(String value) {
            addCriterion("cond_durtime not like", value, "condDurtime");
            return (Criteria) this;
        }

        public Criteria andCondDurtimeIn(List<String> values) {
            addCriterion("cond_durtime in", values, "condDurtime");
            return (Criteria) this;
        }

        public Criteria andCondDurtimeNotIn(List<String> values) {
            addCriterion("cond_durtime not in", values, "condDurtime");
            return (Criteria) this;
        }

        public Criteria andCondDurtimeBetween(String value1, String value2) {
            addCriterion("cond_durtime between", value1, value2, "condDurtime");
            return (Criteria) this;
        }

        public Criteria andCondDurtimeNotBetween(String value1, String value2) {
            addCriterion("cond_durtime not between", value1, value2, "condDurtime");
            return (Criteria) this;
        }

        public Criteria andCondSelectCountIsNull() {
            addCriterion("cond_select_count is null");
            return (Criteria) this;
        }

        public Criteria andCondSelectCountIsNotNull() {
            addCriterion("cond_select_count is not null");
            return (Criteria) this;
        }

        public Criteria andCondSelectCountEqualTo(Integer value) {
            addCriterion("cond_select_count =", value, "condSelectCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondSelectCountEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_select_count = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondSelectCountNotEqualTo(Integer value) {
            addCriterion("cond_select_count <>", value, "condSelectCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondSelectCountNotEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_select_count <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondSelectCountGreaterThan(Integer value) {
            addCriterion("cond_select_count >", value, "condSelectCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondSelectCountGreaterThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_select_count > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondSelectCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("cond_select_count >=", value, "condSelectCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondSelectCountGreaterThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_select_count >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondSelectCountLessThan(Integer value) {
            addCriterion("cond_select_count <", value, "condSelectCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondSelectCountLessThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_select_count < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondSelectCountLessThanOrEqualTo(Integer value) {
            addCriterion("cond_select_count <=", value, "condSelectCount");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCondSelectCountLessThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("cond_select_count <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCondSelectCountIn(List<Integer> values) {
            addCriterion("cond_select_count in", values, "condSelectCount");
            return (Criteria) this;
        }

        public Criteria andCondSelectCountNotIn(List<Integer> values) {
            addCriterion("cond_select_count not in", values, "condSelectCount");
            return (Criteria) this;
        }

        public Criteria andCondSelectCountBetween(Integer value1, Integer value2) {
            addCriterion("cond_select_count between", value1, value2, "condSelectCount");
            return (Criteria) this;
        }

        public Criteria andCondSelectCountNotBetween(Integer value1, Integer value2) {
            addCriterion("cond_select_count not between", value1, value2, "condSelectCount");
            return (Criteria) this;
        }

        public Criteria andQualityUserIdsIsNull() {
            addCriterion("quality_user_ids is null");
            return (Criteria) this;
        }

        public Criteria andQualityUserIdsIsNotNull() {
            addCriterion("quality_user_ids is not null");
            return (Criteria) this;
        }

        public Criteria andQualityUserIdsEqualTo(String value) {
            addCriterion("quality_user_ids =", value, "qualityUserIds");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andQualityUserIdsEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("quality_user_ids = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andQualityUserIdsNotEqualTo(String value) {
            addCriterion("quality_user_ids <>", value, "qualityUserIds");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andQualityUserIdsNotEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("quality_user_ids <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andQualityUserIdsGreaterThan(String value) {
            addCriterion("quality_user_ids >", value, "qualityUserIds");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andQualityUserIdsGreaterThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("quality_user_ids > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andQualityUserIdsGreaterThanOrEqualTo(String value) {
            addCriterion("quality_user_ids >=", value, "qualityUserIds");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andQualityUserIdsGreaterThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("quality_user_ids >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andQualityUserIdsLessThan(String value) {
            addCriterion("quality_user_ids <", value, "qualityUserIds");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andQualityUserIdsLessThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("quality_user_ids < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andQualityUserIdsLessThanOrEqualTo(String value) {
            addCriterion("quality_user_ids <=", value, "qualityUserIds");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andQualityUserIdsLessThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("quality_user_ids <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andQualityUserIdsLike(String value) {
            addCriterion("quality_user_ids like", value, "qualityUserIds");
            return (Criteria) this;
        }

        public Criteria andQualityUserIdsNotLike(String value) {
            addCriterion("quality_user_ids not like", value, "qualityUserIds");
            return (Criteria) this;
        }

        public Criteria andQualityUserIdsIn(List<String> values) {
            addCriterion("quality_user_ids in", values, "qualityUserIds");
            return (Criteria) this;
        }

        public Criteria andQualityUserIdsNotIn(List<String> values) {
            addCriterion("quality_user_ids not in", values, "qualityUserIds");
            return (Criteria) this;
        }

        public Criteria andQualityUserIdsBetween(String value1, String value2) {
            addCriterion("quality_user_ids between", value1, value2, "qualityUserIds");
            return (Criteria) this;
        }

        public Criteria andQualityUserIdsNotBetween(String value1, String value2) {
            addCriterion("quality_user_ids not between", value1, value2, "qualityUserIds");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateUserEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("create_user = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateUserNotEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("create_user <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateUserGreaterThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("create_user > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateUserGreaterThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("create_user >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateUserLessThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("create_user < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateUserLessThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("create_user <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(LocalDateTime value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateTimeEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("create_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateTimeNotEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("create_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(LocalDateTime value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateTimeGreaterThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("create_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateTimeGreaterThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("create_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(LocalDateTime value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateTimeLessThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("create_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCreateTimeLessThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("create_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<LocalDateTime> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andValidIsNull() {
            addCriterion("`valid` is null");
            return (Criteria) this;
        }

        public Criteria andValidIsNotNull() {
            addCriterion("`valid` is not null");
            return (Criteria) this;
        }

        public Criteria andValidEqualTo(String value) {
            addCriterion("`valid` =", value, "valid");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andValidEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("`valid` = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andValidNotEqualTo(String value) {
            addCriterion("`valid` <>", value, "valid");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andValidNotEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("`valid` <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andValidGreaterThan(String value) {
            addCriterion("`valid` >", value, "valid");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andValidGreaterThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("`valid` > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andValidGreaterThanOrEqualTo(String value) {
            addCriterion("`valid` >=", value, "valid");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andValidGreaterThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("`valid` >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andValidLessThan(String value) {
            addCriterion("`valid` <", value, "valid");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andValidLessThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("`valid` < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andValidLessThanOrEqualTo(String value) {
            addCriterion("`valid` <=", value, "valid");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andValidLessThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("`valid` <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andValidLike(String value) {
            addCriterion("`valid` like", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotLike(String value) {
            addCriterion("`valid` not like", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidIn(List<String> values) {
            addCriterion("`valid` in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotIn(List<String> values) {
            addCriterion("`valid` not in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidBetween(String value1, String value2) {
            addCriterion("`valid` between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotBetween(String value1, String value2) {
            addCriterion("`valid` not between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andExecTimeIsNull() {
            addCriterion("exec_time is null");
            return (Criteria) this;
        }

        public Criteria andExecTimeIsNotNull() {
            addCriterion("exec_time is not null");
            return (Criteria) this;
        }

        public Criteria andExecTimeEqualTo(String value) {
            addCriterion("exec_time =", value, "execTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExecTimeEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("exec_time = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExecTimeNotEqualTo(String value) {
            addCriterion("exec_time <>", value, "execTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExecTimeNotEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("exec_time <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExecTimeGreaterThan(String value) {
            addCriterion("exec_time >", value, "execTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExecTimeGreaterThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("exec_time > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExecTimeGreaterThanOrEqualTo(String value) {
            addCriterion("exec_time >=", value, "execTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExecTimeGreaterThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("exec_time >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExecTimeLessThan(String value) {
            addCriterion("exec_time <", value, "execTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExecTimeLessThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("exec_time < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExecTimeLessThanOrEqualTo(String value) {
            addCriterion("exec_time <=", value, "execTime");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExecTimeLessThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("exec_time <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExecTimeLike(String value) {
            addCriterion("exec_time like", value, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeNotLike(String value) {
            addCriterion("exec_time not like", value, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeIn(List<String> values) {
            addCriterion("exec_time in", values, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeNotIn(List<String> values) {
            addCriterion("exec_time not in", values, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeBetween(String value1, String value2) {
            addCriterion("exec_time between", value1, value2, "execTime");
            return (Criteria) this;
        }

        public Criteria andExecTimeNotBetween(String value1, String value2) {
            addCriterion("exec_time not between", value1, value2, "execTime");
            return (Criteria) this;
        }

        public Criteria andDeleteMarkIsNull() {
            addCriterion("delete_mark is null");
            return (Criteria) this;
        }

        public Criteria andDeleteMarkIsNotNull() {
            addCriterion("delete_mark is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteMarkEqualTo(String value) {
            addCriterion("delete_mark =", value, "deleteMark");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andDeleteMarkEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("delete_mark = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeleteMarkNotEqualTo(String value) {
            addCriterion("delete_mark <>", value, "deleteMark");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andDeleteMarkNotEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("delete_mark <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeleteMarkGreaterThan(String value) {
            addCriterion("delete_mark >", value, "deleteMark");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andDeleteMarkGreaterThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("delete_mark > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeleteMarkGreaterThanOrEqualTo(String value) {
            addCriterion("delete_mark >=", value, "deleteMark");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andDeleteMarkGreaterThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("delete_mark >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeleteMarkLessThan(String value) {
            addCriterion("delete_mark <", value, "deleteMark");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andDeleteMarkLessThanColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("delete_mark < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeleteMarkLessThanOrEqualTo(String value) {
            addCriterion("delete_mark <=", value, "deleteMark");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andDeleteMarkLessThanOrEqualToColumn(YyzjCAssignTask.Column column) {
            addCriterion(new StringBuilder("delete_mark <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andDeleteMarkLike(String value) {
            addCriterion("delete_mark like", value, "deleteMark");
            return (Criteria) this;
        }

        public Criteria andDeleteMarkNotLike(String value) {
            addCriterion("delete_mark not like", value, "deleteMark");
            return (Criteria) this;
        }

        public Criteria andDeleteMarkIn(List<String> values) {
            addCriterion("delete_mark in", values, "deleteMark");
            return (Criteria) this;
        }

        public Criteria andDeleteMarkNotIn(List<String> values) {
            addCriterion("delete_mark not in", values, "deleteMark");
            return (Criteria) this;
        }

        public Criteria andDeleteMarkBetween(String value1, String value2) {
            addCriterion("delete_mark between", value1, value2, "deleteMark");
            return (Criteria) this;
        }

        public Criteria andDeleteMarkNotBetween(String value1, String value2) {
            addCriterion("delete_mark not between", value1, value2, "deleteMark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yyzj_c_assign_task
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private YyzjCAssignTaskExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria(YyzjCAssignTaskExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public YyzjCAssignTaskExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table yyzj_c_assign_task
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table yyzj_c_assign_task
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yyzj_c_assign_task
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}