package com.sinosoft.aiqc.db.domain;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class YyzjCUploadAudio {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyzj_c_upload_audio.upload_id
     *
     * @mbg.generated
     */
    private String uploadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyzj_c_upload_audio.sys_id
     *
     * @mbg.generated
     */
    private String sysId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyzj_c_upload_audio.file_name_show
     *
     * @mbg.generated
     */
    private String fileNameShow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyzj_c_upload_audio.file_name_upload
     *
     * @mbg.generated
     */
    private String fileNameUpload;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyzj_c_upload_audio.file_size
     *
     * @mbg.generated
     */
    private Double fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyzj_c_upload_audio.file_format
     *
     * @mbg.generated
     */
    private String fileFormat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyzj_c_upload_audio.upload_user
     *
     * @mbg.generated
     */
    private String uploadUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyzj_c_upload_audio.upload_time
     *
     * @mbg.generated
     */
    private LocalDateTime uploadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyzj_c_upload_audio.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yyzj_c_upload_audio.total_score_id
     *
     * @mbg.generated
     */
    private String totalScoreId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyzj_c_upload_audio.upload_id
     *
     * @return the value of yyzj_c_upload_audio.upload_id
     *
     * @mbg.generated
     */
    public String getUploadId() {
        return uploadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyzj_c_upload_audio.upload_id
     *
     * @param uploadId the value for yyzj_c_upload_audio.upload_id
     *
     * @mbg.generated
     */
    public void setUploadId(String uploadId) {
        this.uploadId = uploadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyzj_c_upload_audio.sys_id
     *
     * @return the value of yyzj_c_upload_audio.sys_id
     *
     * @mbg.generated
     */
    public String getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyzj_c_upload_audio.sys_id
     *
     * @param sysId the value for yyzj_c_upload_audio.sys_id
     *
     * @mbg.generated
     */
    public void setSysId(String sysId) {
        this.sysId = sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyzj_c_upload_audio.file_name_show
     *
     * @return the value of yyzj_c_upload_audio.file_name_show
     *
     * @mbg.generated
     */
    public String getFileNameShow() {
        return fileNameShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyzj_c_upload_audio.file_name_show
     *
     * @param fileNameShow the value for yyzj_c_upload_audio.file_name_show
     *
     * @mbg.generated
     */
    public void setFileNameShow(String fileNameShow) {
        this.fileNameShow = fileNameShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyzj_c_upload_audio.file_name_upload
     *
     * @return the value of yyzj_c_upload_audio.file_name_upload
     *
     * @mbg.generated
     */
    public String getFileNameUpload() {
        return fileNameUpload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyzj_c_upload_audio.file_name_upload
     *
     * @param fileNameUpload the value for yyzj_c_upload_audio.file_name_upload
     *
     * @mbg.generated
     */
    public void setFileNameUpload(String fileNameUpload) {
        this.fileNameUpload = fileNameUpload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyzj_c_upload_audio.file_size
     *
     * @return the value of yyzj_c_upload_audio.file_size
     *
     * @mbg.generated
     */
    public Double getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyzj_c_upload_audio.file_size
     *
     * @param fileSize the value for yyzj_c_upload_audio.file_size
     *
     * @mbg.generated
     */
    public void setFileSize(Double fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyzj_c_upload_audio.file_format
     *
     * @return the value of yyzj_c_upload_audio.file_format
     *
     * @mbg.generated
     */
    public String getFileFormat() {
        return fileFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyzj_c_upload_audio.file_format
     *
     * @param fileFormat the value for yyzj_c_upload_audio.file_format
     *
     * @mbg.generated
     */
    public void setFileFormat(String fileFormat) {
        this.fileFormat = fileFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyzj_c_upload_audio.upload_user
     *
     * @return the value of yyzj_c_upload_audio.upload_user
     *
     * @mbg.generated
     */
    public String getUploadUser() {
        return uploadUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyzj_c_upload_audio.upload_user
     *
     * @param uploadUser the value for yyzj_c_upload_audio.upload_user
     *
     * @mbg.generated
     */
    public void setUploadUser(String uploadUser) {
        this.uploadUser = uploadUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyzj_c_upload_audio.upload_time
     *
     * @return the value of yyzj_c_upload_audio.upload_time
     *
     * @mbg.generated
     */
    public LocalDateTime getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyzj_c_upload_audio.upload_time
     *
     * @param uploadTime the value for yyzj_c_upload_audio.upload_time
     *
     * @mbg.generated
     */
    public void setUploadTime(LocalDateTime uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyzj_c_upload_audio.status
     *
     * @return the value of yyzj_c_upload_audio.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyzj_c_upload_audio.status
     *
     * @param status the value for yyzj_c_upload_audio.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yyzj_c_upload_audio.total_score_id
     *
     * @return the value of yyzj_c_upload_audio.total_score_id
     *
     * @mbg.generated
     */
    public String getTotalScoreId() {
        return totalScoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yyzj_c_upload_audio.total_score_id
     *
     * @param totalScoreId the value for yyzj_c_upload_audio.total_score_id
     *
     * @mbg.generated
     */
    public void setTotalScoreId(String totalScoreId) {
        this.totalScoreId = totalScoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_upload_audio
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", uploadId=").append(uploadId);
        sb.append(", sysId=").append(sysId);
        sb.append(", fileNameShow=").append(fileNameShow);
        sb.append(", fileNameUpload=").append(fileNameUpload);
        sb.append(", fileSize=").append(fileSize);
        sb.append(", fileFormat=").append(fileFormat);
        sb.append(", uploadUser=").append(uploadUser);
        sb.append(", uploadTime=").append(uploadTime);
        sb.append(", status=").append(status);
        sb.append(", totalScoreId=").append(totalScoreId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_upload_audio
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        YyzjCUploadAudio other = (YyzjCUploadAudio) that;
        return (this.getUploadId() == null ? other.getUploadId() == null : this.getUploadId().equals(other.getUploadId()))
            && (this.getSysId() == null ? other.getSysId() == null : this.getSysId().equals(other.getSysId()))
            && (this.getFileNameShow() == null ? other.getFileNameShow() == null : this.getFileNameShow().equals(other.getFileNameShow()))
            && (this.getFileNameUpload() == null ? other.getFileNameUpload() == null : this.getFileNameUpload().equals(other.getFileNameUpload()))
            && (this.getFileSize() == null ? other.getFileSize() == null : this.getFileSize().equals(other.getFileSize()))
            && (this.getFileFormat() == null ? other.getFileFormat() == null : this.getFileFormat().equals(other.getFileFormat()))
            && (this.getUploadUser() == null ? other.getUploadUser() == null : this.getUploadUser().equals(other.getUploadUser()))
            && (this.getUploadTime() == null ? other.getUploadTime() == null : this.getUploadTime().equals(other.getUploadTime()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getTotalScoreId() == null ? other.getTotalScoreId() == null : this.getTotalScoreId().equals(other.getTotalScoreId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yyzj_c_upload_audio
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUploadId() == null) ? 0 : getUploadId().hashCode());
        result = prime * result + ((getSysId() == null) ? 0 : getSysId().hashCode());
        result = prime * result + ((getFileNameShow() == null) ? 0 : getFileNameShow().hashCode());
        result = prime * result + ((getFileNameUpload() == null) ? 0 : getFileNameUpload().hashCode());
        result = prime * result + ((getFileSize() == null) ? 0 : getFileSize().hashCode());
        result = prime * result + ((getFileFormat() == null) ? 0 : getFileFormat().hashCode());
        result = prime * result + ((getUploadUser() == null) ? 0 : getUploadUser().hashCode());
        result = prime * result + ((getUploadTime() == null) ? 0 : getUploadTime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getTotalScoreId() == null) ? 0 : getTotalScoreId().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table yyzj_c_upload_audio
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        uploadId("upload_id", "uploadId", "CHAR", false),
        sysId("sys_id", "sysId", "CHAR", false),
        fileNameShow("file_name_show", "fileNameShow", "VARCHAR", false),
        fileNameUpload("file_name_upload", "fileNameUpload", "VARCHAR", false),
        fileSize("file_size", "fileSize", "DOUBLE", false),
        fileFormat("file_format", "fileFormat", "VARCHAR", false),
        uploadUser("upload_user", "uploadUser", "VARCHAR", false),
        uploadTime("upload_time", "uploadTime", "TIMESTAMP", false),
        status("status", "status", "CHAR", true),
        totalScoreId("total_score_id", "totalScoreId", "CHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yyzj_c_upload_audio
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yyzj_c_upload_audio
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yyzj_c_upload_audio
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yyzj_c_upload_audio
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yyzj_c_upload_audio
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table yyzj_c_upload_audio
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_upload_audio
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_upload_audio
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_upload_audio
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_upload_audio
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_upload_audio
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_upload_audio
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_upload_audio
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_upload_audio
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table yyzj_c_upload_audio
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}